### ISSUE TITLE
Blank input 

### ISSUE THREAD

**Issue by ahmadmrj** [mberneti/react-datepicker2#98] opened 2020-07-20 09:12 UTC
Is there any way to show blank input and not set default value for the DatePicker element?

**Comment by mberneti** [comment] 2020-07-29 12:52
@ahmadmrj 
So sorry that I’m getting to this now. I will check it soon.

**Comment by mberneti** [comment] 2020-08-02 08:14
Duplicate of #102

**Closed by mberneti** 2020-08-02 08:14 UTC
Labels: duplicate
