### ISSUE TITLE
Compact Style

### ISSUE THREAD

**Issue by shayegh** [mberneti/react-datepicker2#61] opened 2019-12-22 06:55 UTC
Hi,
Is there any way to make the DatePicker smaller and have a compact one for smaller devices?

**Comment by mberneti** [comment] 2019-12-22 08:32
Hi @shayegh 
I'll work on it ASAP.
Duplicate of https://github.com/mberneti/react-datepicker2/issues/56

**Closed by mberneti** 2019-12-22 08:32 UTC
